author: Senorihl
title: Senorihl
description: Developer and Software Craftman
tagline: Developer and Software Craftman
title-separator: —
timezone: "Europe/Paris"
permalink: /:year/:month/:slug/
paginate: 6
excerpt_length: 50
date_format: "%B %-d, %Y"
google_tracking_id: G-TCTL9EV6XD
repository: senorihl/senorihl.github.io

social:
  name: Senorihl
  links:
    - https://github.com/senorihl
    - https://www.linkedin.com/in/senorihl
    - https://mastodon.social/@senorihl
    - https://stackoverflow.com/u/senorihl
    - https://bsky.app/profile/senorihl.bsky.social

defaults:
  - scope:
      path: ""
    values:
      seo_description_max_words: 200

exclude: [ package.json, yarn.lock, .idea, node_modules, vendor, gulpfile.js, Gemfile, entrypoint.sh ]

plugins:
  - amp-jekyll
  - jekyll-github-metadata
  - jekyll-minifier
  - jekyll-octicons
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

whitelist:
  - amp-jekyll
  - jekyll-github-metadata
  - jekyll-minifier
  - jekyll-octicons
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

workbox:
  precache_glob_patterns: # Optional
    - "assets/{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html
    - "/aboutme/index.html"
    - "/projects/index.html"

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  startings: [head, body]

social_media:
  github: senorihl
  linkedin: senorihl
  mastodon: senorihl
  stackoverflow: 2414324