title: Senorihl
description: Developer and Software Craftman
title-separator: —
timezone: "Europe/Paris"
permalink: /:year/:month/:slug/
paginate: 6
excerpt_length: 50
date_format: "%B %-d, %Y"
google_tracking_id: UA-70834668-4
repository: senorihl/senorihl.github.io

exclude: [ package.json, yarn.lock, .idea, node_modules, vendor ]

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  startings: [head, body]

social_media:
  github: senorihl
  linkedin: senorihl
  mastodon: senorihl
  stackoverflow: 2414324